# Site settings
author: Malcom F
title: My journey in coding
header-img: img/home-bg.png
email: sora.vista@gmail.com
copyright_name: Malcom F
description: > # this means to ignore newlines until "baseurl:"
  A brief explanation of my experience of Ruby
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Sorasky9

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
